<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ImageBox.Core\ImageBox.Core.csproj" />
		<ProjectReference Include="..\ImageBox.Documentation\ImageBox.Documentation.csproj" />
		<ProjectReference Include="..\ImageBox.Scripting.Abstractions\ImageBox.Scripting.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="./../global.cs" />
	</ItemGroup>

</Project>
