<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="./../global.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ImageBox.Ast\ImageBox.Ast.csproj" />
		<ProjectReference Include="..\ImageBox.Drawing\ImageBox.Drawing.csproj" />
	</ItemGroup>

</Project>
